### ISSUE TITLE
Failed to load symbol 'Polycast_Filter_ImageSize_Configuration_Interface'.

### ISSUE THREAD

**Issue by dilip-nimble** [AndreasBaumgart/Zend_Filter_ImageSize#5]
<h1>An error occurred</h1>
  <h2>Application error</h2>

    
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> Failed to load symbol 'Polycast_Filter_ImageSize_Configuration_Interface'. If this symbol was recently added or moved, your library map may be out of date. You can rebuild the map by running 'arc liberate'. For more information, see: http://www.phabricator.com/docs/phabricator/article/libphutil_Libraries_User_Guide.html  </p>

  <h3>Stack trace:</h3>
  <pre>#0 [internal function]: __phutil_autoload('Polycast_Filter...')
#1 /Applications/MAMP/htdocs/caltex-composer/library/Polycast/Filter/ImageSize/Configuration/Standard.php(8): spl_autoload_call('Polycast_Filter...')
#2 /Applications/MAMP/htdocs/caltex-composer/library/Polycast/Filter/ImageSize.php(30): require_once('/Applications/M...')
#3 /Applications/MAMP/htdocs/caltex-composer/application/modules/front/controllers/CategoryController.php(2): require_once('/Applications/M...')
#4 /Applications/MAMP/htdocs/caltex-composer/library/Zend/Controller/Dispatcher/Standard.php(357): include_once('/Applications/M...')
#5 /Applications/MAMP/htdocs/caltex-composer/library/REST/Controller/Plugin/RestHandler.php(298): Zend_Controller_Dispatcher_Standard->loadClass('CategoryControl...')
#6 /Applications/MAMP/htdocs/caltex-composer/library/REST/Controller/Plugin/RestHandler.php(69): REST_Controller_Plugin_RestHandler->getReflectionClass(Object(REST_Request))
#7 /Applications/MAMP/htdocs/caltex-composer/library/Zend/Controller/Plugin/Broker.php(287): REST_Controller_Plugin_RestHandler->dispatchLoopStartup(Object(REST_Request))
#8 /Applications/MAMP/htdocs/caltex-composer/library/Zend/Controller/Front.php(928): Zend_Controller_Plugin_Broker->dispatchLoopStartup(Object(REST_Request))
#9 /Applications/MAMP/htdocs/caltex-composer/library/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#10 /Applications/MAMP/htdocs/caltex-composer/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /Applications/MAMP/htdocs/caltex-composer/public/index.php(16): Zend_Application->run()
#12 {main}  </pre>

  <h3>Request Parameters:</h3>
  <pre>array (
  'controller' =&gt; 'category',
  'action' =&gt; 'add',
  'module' =&gt; 'front',
)  </pre>

**Comment by dilip-nimble** [comment]
I am facing this problem. Please someone help me.

Zend Version: 1.12

I have placed PolyCast Folder in my Library Folder and have written my code like this

```

 public function addAction()
    {
        $form = new Form_Category();
            
        if ($this->_request->isPost() && $form->isValid($this->_request->getPost())) {
            //print_r($_FILES); die;
            
            require_once 'Polycast/Filter/ImageSize.php';
            require_once 'Polycast/Filter/ImageSize/Strategy/Crop.php';
            require_once 'Polycast/Filter/ImageSize/PathBuilder/Standard.php';
            
          
            $filter = new Polycast_Filter_ImageSize();
            
            $filter->getConfig()
                ->setHeight(100)
                ->setWidth(200);
            $outputPath = $filter->filter($_FILES['ogimage']['tmp_name']);

            $service = new Service_Category();
            $service->put($form->getValues());
            $this->redirect($this->view->url(array('controller' => 'category', 'action' => 'index', 'updated' => true, 'id' => null), null, true));
        }

        $this->view->title = 'Add';
        $this->view->form = $form;
        $this->_helper->layout->setLayout('innerlayout');
    }
```
